/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.ostenant.rpc.thrift.examples.thrift.enums;


import org.apache.thrift.TEnum;

public enum ThriftRegion implements TEnum {
  NORTH(1),
  CENTRAL(2),
  SOUTH(3),
  EAST(4),
  SOUTHWEST(5),
  NORTHWEST(6),
  NORTHEAST(7);

  private final int value;

  private ThriftRegion(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ThriftRegion findByValue(int value) {
    switch (value) {
      case 1:
        return NORTH;
      case 2:
        return CENTRAL;
      case 3:
        return SOUTH;
      case 4:
        return EAST;
      case 5:
        return SOUTHWEST;
      case 6:
        return NORTHWEST;
      case 7:
        return NORTHEAST;
      default:
        return null;
    }
  }
}
