/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.ostenant.rpc.thrift.examples.thrift.enums;


import org.apache.thrift.TEnum;

public enum ThriftDepositStatus implements TEnum {
  FINISHED(1),
  PROCCEDING(2),
  FAILED(3);

  private final int value;

  private ThriftDepositStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ThriftDepositStatus findByValue(int value) {
    switch (value) {
      case 1:
        return FINISHED;
      case 2:
        return PROCCEDING;
      case 3:
        return FAILED;
      default:
        return null;
    }
  }
}
